GuestBook/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    collection do
      get :surprise
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

GuestBook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GuestBook/app/models/post.rb
class Post < ApplicationRecord
  before_create :titleize_author

  private
  def titleize_author
    self.author = self.author.to_s.titleize
  end
end

GuestBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

GuestBook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Dziękujemy za wpis"
          redirect_to posts_path
        end
        format.js { }
      end
    end
  end

  def surprise
  end

  private
  def post_params
    params.require(:post).permit(:author, :body)
  end
end

GuestBook/app/helpers/application_helper.rb
module ApplicationHelper
end

GuestBook/app/helpers/posts_helper.rb
module PostsHelper
end

GuestBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuestBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <h1>Księga Gości</h1>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

GuestBook/app/views/posts/_surprise-content.html.erb
<div class="jumbotron">
  <h1>Niespodzianka</h1>
  <p>To jest bardzo fajna niespodzianka</p>
  <p><%= link_to "Sprawdź to", posts_path, class: "btn btn-lg btn-primary" %></p>
</div>

GuestBook/app/views/posts/create.js.erb
$("#form-container").hide(500, function() {
  $("#form-containder").html("<p class=\"alert alert-success\">Dziękujemy za wpis!</p>");
  $("#form-containder").show(500);
});

GuestBook/app/views/posts/index.html.erb
<p class="lead">
  Witaj w naszej Księdze Gości!
  <%= link_to "Dodaj wpis", new_post_path %>
</p>

<div id="container-placeholder">
  <%= link_to "Niespodzianka", surprise_posts_path, class: "btn btn-info", remote: true %>
</div>

<% @posts.each do |post| %>
  <blockquote>
    <p><%= post.body %></p>
    <footer><cite><%= post.author %></cite></footer>
  </blockquote>
<% end %>

GuestBook/app/views/posts/new.html.erb
<h2> Dodawanie nowego wpisu</h2>

<div id="form-container">
  <%= form_for @post, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :author, "Autor" %>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body, "Treść" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit "Dodaj wpis", class: "btn btn-default" %>
  <% end %>
</div>

GuestBook/app/views/posts/surprise.js.erb
//alert("Hello World! <%= Time.now.beginning_of_year %>");
$("#container-placeholder").html("<%= escape_javascript(render(partial: "surprise-content")) %>");